In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset, columns = ["sex", "smoker"], drop_first= True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [5]:
indep = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
indep

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
dep = dataset[["charges"]]
dep

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error', 'absolute_error', 'poisson'],'splitter': ['best', 'random']}

In [9]:
grid = GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True, verbose = 3, n_jobs= -1)

In [10]:
grid.fit(indep,dep)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [11]:
re = grid.cv_results_
print("The R_score Value for best parameter {}:".format(grid.best_params_))

The R_score Value for best parameter {'criterion': 'poisson', 'splitter': 'best'}:

In [12]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.442330,0.099395,0.023257,0.008603,squared_error,best,"{'criterion': 'squared_error', 'splitter': 'be...",0.710610,0.618518,0.728916,0.700242,0.676231,0.686903,0.038198,5
1,0.428947,0.082222,0.054712,0.033924,squared_error,random,"{'criterion': 'squared_error', 'splitter': 'ra...",0.724569,0.651289,0.748106,0.697962,0.719224,0.708230,0.032636,2
2,0.451648,0.152596,0.021816,0.010753,absolute_error,best,"{'criterion': 'absolute_error', 'splitter': 'b...",0.715838,0.615512,0.704516,0.733110,0.735235,0.700842,0.044144,3
3,0.229026,0.039946,0.027939,0.013596,absolute_error,random,"{'criterion': 'absolute_error', 'splitter': 'r...",0.739496,0.520599,0.751201,0.706180,0.744172,0.692330,0.087248,4
4,0.077629,0.027608,0.058649,0.038501,poisson,best,"{'criterion': 'poisson', 'splitter': 'best'}",0.746944,0.657801,0.759520,0.724805,0.705452,0.718904,0.035736,1
5,0.056363,0.030415,0.014968,0.004070,poisson,random,"{'criterion': 'poisson', 'splitter': 'random'}",0.698166,0.595919,0.698799,0.730082,0.699562,0.684506,0.045918,6

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 28
BMI: 36
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[3693.428]

C:\Users\sridi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(