In [1]:
import pandas as pd

In [3]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, columns = ["sex", "smoker"], drop_first= True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [6]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [7]:
dependent = dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [10]:
x_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [50]:
from sklearn.svm import SVR
regressor = SVR(kernel='sigmoid', C = 3000)
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

C:\Users\sridi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-2.1244194786689854

In [51]:
# regressor = SVR(kernel='linear', C = 1) ====> r_score = -0.010102665316081394
# regressor = SVR(kernel='linear', C = 10) ====> r_score = 0.46246841423396834
# regressor = SVR(kernel='linear', C = 100) ====> r_score = 0.6288792857320369
# regressor = SVR(kernel='linear', C = 1000) ====> r_score = 0.7649311738597411
# regressor = SVR(kernel='linear', C = 2000) ====> r_score = 0.7440418308107846
# regressor = SVR(kernel='linear', C = 3000) ====> r_score = 0.7414236599249833

In [52]:
# regressor = SVR(kernel='rbf', C = 1) ====> r_score = -0.08338238593619329
# regressor = SVR(kernel='rbf', C = 10) ====> r_score = -0.03227329390671052
# regressor = SVR(kernel='rbf', C = 100) ====> r_score = 0.3200317832050831
# regressor = SVR(kernel='rbf', C = 1000) ====> r_score = 0.8102064851758545
# regressor = SVR(kernel='rbf', C = 2000) ====> r_score = 0.8547766425392979
# regressor = SVR(kernel='rbf', C = 3000) ====> r_score = 0.8663393953081687

In [53]:
# regressor = SVR(kernel='poly', C = 1) ====> r_score = -0.07569965570860893
# regressor = SVR(kernel='poly', C = 10) ====> r_score = 0.038716222760231456
# regressor = SVR(kernel='poly', C = 100) ====> r_score = 0.6179569624059795
# regressor = SVR(kernel='poly', C = 1000) ====> r_score = 0.6179569624059795
# regressor = SVR(kernel='poly', C = 2000) ====> r_score = 0.8605579258597704
# regressor = SVR(kernel='poly', C = 3000) ====> r_score = 0.8598930084494356

In [54]:
# regressor = SVR(kernel='sigmoid', C = 1) ====> r_score = -0.07542924281107188
# regressor = SVR(kernel='sigmoid', C = 10) ====> r_score = 0.03930714378274347
# regressor = SVR(kernel='sigmoid', C = 100) ====> r_score = 0.5276103546510407
# regressor = SVR(kernel='sigmoid', C = 1000) ====> r_score = 0.28747069486976173
# regressor = SVR(kernel='sigmoid', C = 2000) ====> r_score = -0.5939509731283503
# regressor = SVR(kernel='sigmoid', C = 3000) ====> r_score = -2.1244194786689854